version: '3'
services:
  web:
    image: my-django-app
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - npm_public
    ports:
      - 8000:8000

networks:
  npm_public:
    external: true